name: Run tests

on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:4.10.3
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        run: conda env create --file conda.yml

      - name: Execute Tests
        run: |
          conda init bash && conda activate fides && pytest tests
