name: Run tests

on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: conda.yml
          activate-environment: fides

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Execute Tests
        shell: bash -l {0}
        run: pytest tests

  generate-and-release-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: xu-cheng/latex-action@v2
        name: Build Thesis PDF
        with:
          working_directory: thesis
          root_file: main.tex

      - uses: actions/upload-artifact@v2
        name: Upload PDF
        with:
          name: PDF
          path: thesis/main.pdf

      - name: Get Release Name
        run: echo "RELEASE_NAME=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ env.RELEASE_NAME }}
          files: thesis/main.pdf
